# Site settings
title: Anathematherne
email: projects.Matherne@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: matherne_austin
github_username:  amatherne

# Build settings
markdown: kramdown
