# Site settings
title: Austin Matherne
email: projects.Matherne@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: matherne_austin
github_username:  amatherne
# excerpt_separator: <!--excerpt break-->


paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
